services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: stack.env
    ports:
      - "8889:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  pgadmin-data:
    name: pgadmin-data
    driver_opts:
      type: "nfs"
      o: addr=ip,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :/mnt/nfs-path/docker-data/pgadmin