---
services:
  gitea:
    image: docker.io/gitea/gitea:1.24.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${POSTGRES_HOST}:${POSTGRES_PORT}
      - GITEA__database__NAME=${POSTGRES_DB:?POSTGRES_DB not set}
      - GITEA__database__USER=${POSTGRES_USER:?POSTGRES_USER not set}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      - GITEA__server__SSH_PORT=222  # <-- (Optional) Replace with your desired SSH port
      - GITEA__server__ROOT_URL=https://gitea.hamiltonhills.io  # <-- Replace with your FQDN
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3002:3000"
      - "222:22"  # <-- (Optional) Replace with your desired SSH port
    restart: unless-stopped

volumes:
  gitea-data:
    name: gitea-data
    driver_opts:
      type: "nfs"
      o: addr=ip,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :/mnt/nfs-path/gitea/data